language: php

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: OLDPHP=true
    - php: 5.4
      env: OLDPHP=true
    - php: 5.5
      env: OLDPHP=true
    - php: 5.6
      env: OLDPHP=true
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly

install:
  - if [[ $OLDPHP == true ]]; then composer require "phpunit/phpunit:5.7"; fi
  - if [[ $OLDPHP != true ]]; then composer install; fi

script: phpunit --bootstrap vendor/autoload.php tests
