language: php

env:
  global:
    - setup=stable

matrix:
  include:
    - php: 5.5
      env: OLDPHP=true
    - php: 5.6
      env: OLDPHP=true
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly

install: composer install

script: phpunit --bootstrap vendor/autoload.php tests
